package main

import (
	"encoding/json"
	"fmt"
)

type AA struct {
	Name string `json:"name"`
}

type AutoGenerated struct {
	Age   int    `json:"age"`
	Name  string `json:"name"`
	Child []*int `json:"child"`
	AA    *AA    `json:"aa"`
}

func main() {
	jsonStr1 := `{"age": 14,"name": "potter"}`
	a := AutoGenerated{}
	json.Unmarshal([]byte(jsonStr1), &a)
	aa := a.Child
	fmt.Println(aa)
	jsonStr2 := `{"age": 12,"name": "potter", "child":[3,4,5,7,8,9]}`
	json.Unmarshal([]byte(jsonStr2), &a)
	fmt.Println(a.Child, aa)

	fmt.Println()
	jsonStr3 := `{"age": 14,"name": "potter"}`
	b := AutoGenerated{}
	json.Unmarshal([]byte(jsonStr3), &b)
	fmt.Printf("b : %+v\n", b)

}
